"""atletas

Revision ID: 47572d824072
Revises: c006e8463eb4
Create Date: 2024-04-28 17:06:17.227645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47572d824072'
down_revision = 'c006e8463eb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
